### ISSUE TITLE
Consider writing a short tutorial explaining how to use this

### ISSUE THREAD

**Issue by wallrj** [james-callahan/cert-manager-kustomize#18]
I'd be interested to learn how you install these configurations.
Do you use `kustomize` CLI or do you install them using `flux` or `argo`?

I've been writing a new [Continuous Deployment section on cert-manager.io ](https://cert-manager.io/docs/installation/continuous-deployment-and-gitops/) and I thought it might be useful to mention this project there.

**Comment by james-callahan** [comment]
> Do you use `kustomize` CLI or do you install them using `flux` or `argo`?

I've used both.

  - For a super quick start, you can run `kubectl apply -k github.com/james-callahan/cert-manager-kustomize`
  - For a quick start, you can run: `kustomize build github.com/james-callahan/cert-manager-kustomize | kubectl apply -f -`
  - For a more normal use case, you'd write your own `kustomization.yaml` file in your own gitops repository with some chages particular to your deployment. Here is one I have:
  ```yaml
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  namespace: cert-manager
  commonLabels:
    app.kubernetes.io/name: cert-manager
  resources:
    - github.com/james-callahan/cert-manager-kustomize?ref=22b0e4211f469ec497306e67bc487423e489e8c6 # branch=main
    - github.com/james-callahan/cert-manager-kustomize/controller/servicemonitor?ref=22b0e4211f469ec497306e67bc487423e489e8c6 # branch=main
    - myclusterissuer.yaml
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: cert-manager
        spec:
          template:
            spec:
              containers:
                - name: cert-manager-controller
                  resources:
                    requests:
                      memory: 35Mi
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: cert-manager-cainjector
        spec:
          template:
            spec:
              containers:
                - name: cert-manager-cainjector
                  resources:
                    requests:
                      memory: 50Mi
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: cert-manager-webhook
        spec:
          template:
            spec:
              containers:
                - name: cert-manager-webhook
                  resources:
                    requests:
                      memory: 20Mi
  ```
  You can then either use that locally via `kustomize build ./the_directory_with_that_file_in_it| kubectl apply -f -`, or hand that repository/directory over to e.g. ArgoCD.
